spring.application.name=smart-task-manager

logging.level.root=INFO
logging.level.com.example.smart_task_manager=DEBUG

logging.file.name=logs/application.log

jwt.secret=mySuperSecretKeyForJwtAuthentication1234567890ABCDEF

jwt.access-token-expiration=900000

jwt.refresh-token-expiration=604800000